//
//  LoginVIPPresenter.swift
//  MentalHealthApp
//
//  Created by Dato Khvedelidze on 02.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginVIPPresentationLogic {
    func presentUserValidationOutcome(response: LoginVIP.UserValidation.Response)
}

final class LoginVIPPresenter {
    // MARK: - Clean Components
    
    weak var viewController: LoginVIPDisplayLogic?
}

// MARK: - LoginVIPPresentationLogic

extension LoginVIPPresenter: LoginVIPPresentationLogic {
    func presentUserValidationOutcome(response: LoginVIP.UserValidation.Response) {
        let viewModel = LoginVIP.UserValidation.ViewModel(outcome: response.outcome, isError: response.isError)
        
        viewController?.displayUserValidationOutcome(viewModel: viewModel)
    }
}
