//
//  LoginInteractor.swift
//  MentalHealthApp
//
//  Created by Dato Khvedelidze on 02.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginBusinessLogic {
    func validateUser(request: Login.UserValidation.Request)
}

final class LoginInteractor {
    // MARK: - Clean Components
    
    var presenter: LoginPresentationLogic?
    var worker: LoginWorkerLogic?
}

// MARK: - LoginBusinessLogic

extension LoginInteractor: LoginBusinessLogic {
    func validateUser(request: Login.UserValidation.Request) {
        
        guard let email = request.email?.trimmingCharacters(in: .whitespacesAndNewlines),
              let password = request.password?.trimmingCharacters(in: .whitespacesAndNewlines) else { return }
        
        if email == Constant.String.empty || password == Constant.String.empty {
            presenter?.presentUserValidationOutcome(response: Login.UserValidation.Response(outcome: Constant.ValidationOutcome.notAllFieldsFilled, isError: true))
        } else {
            worker?.loginUser(email: email,
                              password: password,
                              completionHandler: { [weak self] (outcome, isError) in
                let response = Login.UserValidation.Response(outcome: outcome, isError: isError)
                self?.presenter?.presentUserValidationOutcome(response: response)
            })
        }
    }
}
