//
//  LoginVIPRouter.swift
//  MentalHealthApp
//
//  Created by Dato Khvedelidze on 02.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginVIPRoutingLogic {
    func routeToRegistrationVC()
    func routeToTabBarVC()
}

final class LoginVIPRouter: LoginVIPRoutingLogic {
    // MARK: - Clean Components
    
    weak var viewController: LoginVIPViewController?
    private let storyboard = UIStoryboard(name: "Main", bundle: nil)
    
    // MARK: - Routing
    
    func routeToRegistrationVC() {
        let registrationVC = storyboard.instantiateViewController(withIdentifier: "RegistrationVIPViewController") as! RegistrationVIPViewController
        navigateToRegistrationVC(source: viewController!, destination: registrationVC)
    }
    
    func routeToTabBarVC() {
        let tabBarController = TabBarController()
        
        let homeVC = storyboard.instantiateViewController(withIdentifier: "HomeScreenViewController") as! HomeScreenViewController
        
        let profileVC = storyboard.instantiateViewController(withIdentifier: "ProfileViewController") as! ProfileViewController
        
        Utilities.setupTabBarItem(homeVC, Image.inactiveHome, Image.activeHome)
        Utilities.setupTabBarItem(profileVC, Image.inactiveProfile, Image.activeProfile)
        
        tabBarController.viewControllers = [homeVC, profileVC]
        
        navigateToTabBarVC(source: viewController!, destination: tabBarController)
    }
    
    // MARK: - Navigation
    
    func navigateToRegistrationVC(source: LoginVIPViewController, destination: RegistrationVIPViewController) {
        source.navigationController?.pushViewController(destination, animated: true)
    }
    
    func navigateToTabBarVC(source: LoginVIPViewController, destination: TabBarController) {
        DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
            source.view.window?.switchRootViewController(destination, animated: true, duration: 0.5, options: .transitionCrossDissolve, completion: nil)
        }
    }
}
