//
//  LoginVIPInteractor.swift
//  MentalHealthApp
//
//  Created by Dato Khvedelidze on 02.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginVIPBusinessLogic {
    func validateUser(request: LoginVIP.UserValidation.Request)
}

final class LoginVIPInteractor {
    // MARK: - Clean Components
    
    var presenter: LoginVIPPresentationLogic?
    var worker: LoginVIPWorkerLogic?
}


// MARK: - LoginVIPBusinessLogic

extension LoginVIPInteractor: LoginVIPBusinessLogic {
    func validateUser(request: LoginVIP.UserValidation.Request) {
        
        guard let email = request.email?.trimmingCharacters(in: .whitespacesAndNewlines),
              let password = request.password?.trimmingCharacters(in: .whitespacesAndNewlines) else { return }
        
        if email == "" || password == "" {
            let response = LoginVIP.UserValidation.Response(outcome: Constant.ValidationOutcome.notAllFieldsFilled, isError: true)
            presenter?.presentUserValidationOutcome(response: response)
        } else {
            worker = LoginVIPWorker()
            worker?.loginUser(email: email, password: password, completionHandler: { [weak self] (outcome, isError) in
                let response = LoginVIP.UserValidation.Response(outcome: outcome, isError: isError)
                self?.presenter?.presentUserValidationOutcome(response: response)
            })
        }
    }
}
