//
//  LoginWorker.swift
//  MentalHealthApp
//
//  Created by Dato Khvedelidze on 02.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Firebase
import FirebaseAuth

protocol LoginWorkerLogic {
    func loginUser(email: String, password: String, completionHandler: @escaping (String, Bool) -> ())
}

final class LoginWorker { }

// MARK: - LoginWorkerLogic

extension LoginWorker: LoginWorkerLogic {
    func loginUser(email: String, password: String, completionHandler: @escaping (String, Bool) -> ()) {
        AuthService.loginUser(withEmail: email, password: password) { result, error in
            if error != nil {
                completionHandler(error!.localizedDescription, true)
            } else {
                completionHandler(Constant.ValidationOutcome.successfulLogin, false)
            }
        }
    }
}
