//
//  LoginRouter.swift
//  MentalHealthApp
//
//  Created by Dato Khvedelidze on 02.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginRoutingLogic {
    func routeToRegistrationVC()
    func routeToTabBarVC()
}

final class LoginRouter: LoginRoutingLogic {
    // MARK: - Clean Components
    
    weak var viewController: LoginViewController?

    // MARK: - Routing
    
    func routeToRegistrationVC() {
        let registrationStoryboard = UIStoryboard(name: Constant.StoryboardIdentifier.registration, bundle: nil)
        guard let registrationVC = registrationStoryboard.instantiateViewController(withIdentifier: Constant.ViewControllerIdentifier.registrationVC) as? RegistrationViewController else { return }
        guard let viewController = viewController else { return }
        navigateToRegistrationVC(source: viewController, destination: registrationVC)
    }
    
    func routeToTabBarVC() {
        let homeStoryboard = UIStoryboard(name: Constant.StoryboardIdentifier.home, bundle: nil)
        let profileStoryboard = UIStoryboard(name: Constant.StoryboardIdentifier.profile, bundle: nil)
        
        guard let homeVC = homeStoryboard.instantiateViewController(withIdentifier: Constant.ViewControllerIdentifier.homeVC) as? HomeViewController else { return }
        guard let profileVC = profileStoryboard.instantiateViewController(withIdentifier: Constant.ViewControllerIdentifier.profileVC) as? ProfileViewController else { return }
        guard let viewController = viewController else { return }
        
        let tabBarController = Utilities.setupTabBar(with: [homeVC, profileVC])
        
        Utilities.setupTabBarItem(for: homeVC, Constant.Image.inactiveHome, Constant.Image.activeHome)
        Utilities.setupTabBarItem(for: profileVC, Constant.Image.inactiveProfile, Constant.Image.activeProfile)
        
        navigateToTabBarVC(source: viewController, destination: tabBarController)
    }
    
    // MARK: - Navigation
    
    func navigateToRegistrationVC(source: LoginViewController, destination: RegistrationViewController) {
        source.navigationController?.pushViewController(destination, animated: true)
    }
    
    func navigateToTabBarVC(source: LoginViewController, destination: UITabBarController) {
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.5) {
            source.view.window?.switchRootViewController(destination, animated: true, duration: 0.5, options: .transitionCrossDissolve)
        }
    }
}
