//
//  LoginPresenter.swift
//  MentalHealthApp
//
//  Created by Dato Khvedelidze on 02.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic {
    func presentUserValidationOutcome(response: Login.UserValidation.Response)
}

final class LoginPresenter {
    // MARK: - Clean Components
    
    weak var viewController: LoginDisplayLogic?
}

// MARK: - LoginPresentationLogic

extension LoginPresenter: LoginPresentationLogic {
    func presentUserValidationOutcome(response: Login.UserValidation.Response) {
        let viewModel = Login.UserValidation.ViewModel(outcome: response.outcome, isError: response.isError)
        
        viewController?.displayUserValidationOutcome(viewModel: viewModel)
    }
}
