//
//  ProfilePresenter.swift
//  MentalHealthApp
//
//  Created by Dato Khvedelidze on 06.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProfilePresentationLogic {
    func presentUserInfo(response: Profile.GetUserInfo.Response)
}

final class ProfilePresenter {
    // MARK: - Clean Components
    
    weak var viewController: ProfileDisplayLogic?
}

// MARK: - ProfilePresentationLogic

extension ProfilePresenter: ProfilePresentationLogic {
    func presentUserInfo(response: Profile.GetUserInfo.Response) {
        guard let user = response.user else { return }
        let viewModel = Profile.GetUserInfo.ViewModel(fullname: "\(user.firstname) \(user.lastname)", likedQuotes: user.liked_quotes)
        viewController?.displayUserInfo(viewModel: viewModel)
    }
}
