//
//  ProfileVIPPresenter.swift
//  MentalHealthApp
//
//  Created by Dato Khvedelidze on 06.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProfileVIPPresentationLogic {
    func presentUserInfo(response: ProfileVIP.GetUserInfo.Response)
}

final class ProfileVIPPresenter {
    // MARK: - Clean Components
    
    weak var viewController: ProfileVIPDisplayLogic?
}

// MARK: - ProfileVIPPresentationLogic

extension ProfileVIPPresenter: ProfileVIPPresentationLogic {
    func presentUserInfo(response: ProfileVIP.GetUserInfo.Response) {
        guard let user = response.user else { return }
        let viewModel = ProfileVIP.GetUserInfo.ViewModel(fullname: "\(user.firstname) \(user.lastname)", likedQuotes: user.liked_quotes)
        viewController?.displayUserInfo(viewModel: viewModel)
    }
}
