//
//  ProfileVIPInteractor.swift
//  MentalHealthApp
//
//  Created by Dato Khvedelidze on 06.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProfileVIPBusinessLogic {
    func getUserInfo(request: ProfileVIP.GetUserInfo.Request)
}

final class ProfileVIPInteractor {
    // MARK: - Clean Components
    
    var presenter: ProfileVIPPresentationLogic?
    var worker: ProfileVIPWorker?
}

// MARK: - ProfileVIPBusinessLogic

extension ProfileVIPInteractor: ProfileVIPBusinessLogic {
    func getUserInfo(request: ProfileVIP.GetUserInfo.Request) {
        UserService.fetchUser(detach: false) { [weak self] user in
            let response = ProfileVIP.GetUserInfo.Response(user: user)
            self?.presenter?.presentUserInfo(response: response)
        }
    }
}
