//
//  ProfileInteractor.swift
//  MentalHealthApp
//
//  Created by Dato Khvedelidze on 06.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProfileBusinessLogic {
    func getUserInfo(request: Profile.GetUserInfo.Request)
}

final class ProfileInteractor {
    // MARK: - Clean Components
    
    var presenter: ProfilePresentationLogic?
    var worker: ProfileWorker?
}

// MARK: - ProfileBusinessLogic

extension ProfileInteractor: ProfileBusinessLogic {
    func getUserInfo(request: Profile.GetUserInfo.Request) {
        UserService.fetchUser(detach: false) { [weak self] user in
            let response = Profile.GetUserInfo.Response(user: user)
            self?.presenter?.presentUserInfo(response: response)
        }
    }
}
