//
//  HomeModels.swift
//  MentalHealthApp
//
//  Created by Dato Khvedelidze on 04.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Home {
    // MARK: - Use cases
    
    enum GetUser {
        struct Request { }
        struct Response {
            let user: User
        }
        struct ViewModel {
            let user: String
        }
    }
    
    enum GetQuote {
        struct Request { }
        struct Response {
            let quote: Quote?
        }
        struct ViewModel {
            let quote: String
        }
    }
    
    enum UpdateLikedQuotes {
        struct Request {
            let quote: String?
            let clickedLike: Bool
        }
        struct Response { }
        struct ViewModel { }
    }

}
