//
//  HomeVIPInteractor.swift
//  MentalHealthApp
//
//  Created by Dato Khvedelidze on 04.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeVIPBusinessLogic {
    func getUser(request: HomeVIP.GetUser.Request)
    func getQuote(request: HomeVIP.GetQuote.Request)
    func updateLikedQuotes(request: HomeVIP.UpdateLikedQuotes.Request)
}

final class HomeVIPInteractor {
    // MARK: - Clean Components
    
    var presenter: HomeVIPPresentationLogic?
    var worker: HomeVIPWorker?
    
}

// MARK: - HomeVIPBusinessLogic

extension HomeVIPInteractor: HomeVIPBusinessLogic {
    func getUser(request: HomeVIP.GetUser.Request) {
        UserService.fetchUser(detach: false) { [weak self] user in
            let response = HomeVIP.GetUser.Response(user: user)
            self?.presenter?.presentUser(response: response)
        }
    }
    
    
    
    func getQuote(request: HomeVIP.GetQuote.Request) {
        worker = HomeVIPWorker()
        
        Task {
            do {
                let quote = try await worker?.fetchQuote()
                DispatchQueue.main.async { [weak self] in
                    let response = HomeVIP.GetQuote.Response(quote: quote)
                    self?.presenter?.presentQuote(response: response)
                }
            }
        }
    }
    
    func updateLikedQuotes(request: HomeVIP.UpdateLikedQuotes.Request) {
        guard let quote = request.quote else { return }
        let condition = request.clickedLike
        
        UserService.updateLikedQuotesArray(condition: condition, quote: quote)
    }
    
}
