//
//  HomeVIPPresenter.swift
//  MentalHealthApp
//
//  Created by Dato Khvedelidze on 04.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeVIPPresentationLogic {
    func presentUser(response: HomeVIP.GetUser.Response)
    func presentQuote(response: HomeVIP.GetQuote.Response)
}

final class HomeVIPPresenter {
    // MARK: - Clean Components
    
    weak var viewController: HomeVIPDisplayLogic?
}

// MARK: - HomeVIPPresentationLogic

extension HomeVIPPresenter: HomeVIPPresentationLogic {
    func presentUser(response: HomeVIP.GetUser.Response) {
        let welcomeString = "Welcome, \(response.user.firstname) \n How are you feeling today?"
        let viewModel = HomeVIP.GetUser.ViewModel(user: welcomeString)
        
        viewController?.displayUser(viewModel: viewModel)
    }
    
    func presentQuote(response: HomeVIP.GetQuote.Response) {
        guard let quote = response.quote else { return }
        let quoteToPresent = "\(quote.content) \n - \(quote.author)"
        let viewModel = HomeVIP.GetQuote.ViewModel(quote: quoteToPresent)
        
        viewController?.displayQuote(viewModel: viewModel)
    }
}
