//
//  HomeVIPWorker.swift
//  MentalHealthApp
//
//  Created by Dato Khvedelidze on 04.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeVIPWorkerLogic {
    func fetchQuote() async throws -> Quote
}

final class HomeVIPWorker {
    // MARK: - Fields
    
    private var networkService = NetworkService()
}

// MARK: - HomeVIPWorkerLogic

extension HomeVIPWorker: HomeVIPWorkerLogic {
    func fetchQuote() async throws -> Quote {
        try await networkService.fetchQuotes()
    }
}
