//
//  HomeRouter.swift
//  MentalHealthApp
//
//  Created by Dato Khvedelidze on 04.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeRoutingLogic { }

final class HomeRouter: HomeRoutingLogic {
    // MARK: - Clean Components
    
    weak var viewController: HomeViewController?
}
