//
//  HomePresenter.swift
//  MentalHealthApp
//
//  Created by Dato Khvedelidze on 04.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic {
    func presentUser(response: Home.GetUser.Response)
    func presentQuote(response: Home.GetQuote.Response)
}

final class HomePresenter {
    // MARK: - Clean Components
    
    weak var viewController: HomeDisplayLogic?
}

// MARK: - HomePresentationLogic

extension HomePresenter: HomePresentationLogic {
    func presentUser(response: Home.GetUser.Response) {
        let welcomeString = "Welcome, \(response.user.firstname) \n How are you feeling today?"
        
        viewController?.displayUser(viewModel: Home.GetUser.ViewModel(user: welcomeString))
    }
    
    func presentQuote(response: Home.GetQuote.Response) {
        guard let quote = response.quote else { return }
        let quoteToPresent = "\(quote.content) \n - \(quote.author)"
        let viewModel = Home.GetQuote.ViewModel(quote: quoteToPresent)
        
        viewController?.displayQuote(viewModel: viewModel)
    }
}
