//
//  RegistrationVIPWorker.swift
//  MentalHealthApp
//
//  Created by Dato Khvedelidze on 03.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RegistrationVIPWorkerLogic {
    func registerUser(withEmail email: String, password: String, firstname: String, lastname: String, completionHandler: @escaping (String, Bool) -> ())
}

final class RegistrationVIPWorker { }

// MARK: - RegistrationVIPWorkerLogic

extension RegistrationVIPWorker: RegistrationVIPWorkerLogic {
    func registerUser(withEmail email: String, password: String, firstname: String, lastname: String, completionHandler: @escaping (String, Bool) -> ()) {
        AuthService.registerUser(withEmail: email, password: password) { result, error in
            if error != nil {
                completionHandler(error!.localizedDescription, true)
            } else {
                UserService.registerInDB(with: firstname, lastname: lastname, uid: result!.user.uid)
                completionHandler(Constant.ValidationOutcome.successfulRegistration, false)
            }
        }
    }
}
