//
//  RegistrationVIPModels.swift
//  MentalHealthApp
//
//  Created by Dato Khvedelidze on 03.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum RegistrationVIP {
  // MARK: - Use cases
  
  enum RegistrationValidation {
    struct Request {
        let firstname: String?
        let lastname: String?
        let email: String?
        let password: String?
        let confirmPassword: String?
    }
    struct Response {
        let outcome: String?
        let isError: Bool
    }
    struct ViewModel {
        let outcome: String?
        let isError: Bool
    }
  }
}
