//
//  RegistrationVIPPresenter.swift
//  MentalHealthApp
//
//  Created by Dato Khvedelidze on 03.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RegistrationVIPPresentationLogic {
    func presentRegistrationOutcome(response: RegistrationVIP.RegistrationValidation.Response)
}

final class RegistrationVIPPresenter {
    // MARK: - Clean Components
    
    weak var viewController: RegistrationVIPDisplayLogic?
}

// MARK: - RegistrationVIPPresentationLogic

extension RegistrationVIPPresenter: RegistrationVIPPresentationLogic {
    func presentRegistrationOutcome(response: RegistrationVIP.RegistrationValidation.Response) {
        let viewModel = RegistrationVIP.RegistrationValidation.ViewModel(outcome: response.outcome, isError: response.isError)
        viewController?.displayRegistrationOutcome(viewModel: viewModel)
    }
}
