//
//  RegistrationVIPInteractor.swift
//  MentalHealthApp
//
//  Created by Dato Khvedelidze on 03.09.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RegistrationVIPBusinessLogic {
    func validateRegistration(request: RegistrationVIP.RegistrationValidation.Request)
}

final class RegistrationVIPInteractor {
    //MARK: - Clean Components
    
    var presenter: RegistrationVIPPresentationLogic?
    var worker: RegistrationVIPWorkerLogic?
}

// MARK: - RegistrationVIPBusinessLogic

extension RegistrationVIPInteractor: RegistrationVIPBusinessLogic {
    
    func validateRegistration(request: RegistrationVIP.RegistrationValidation.Request) {
        guard let firstname = request.firstname?.trimmingCharacters(in: .whitespacesAndNewlines),
              let lastname = request.lastname?.trimmingCharacters(in: .whitespacesAndNewlines),
              let email = request.email?.trimmingCharacters(in: .whitespacesAndNewlines),
              let password = request.password?.trimmingCharacters(in: .whitespacesAndNewlines),
              let confirmPassword = request.confirmPassword?.trimmingCharacters(in: .whitespacesAndNewlines) else { return }
        
        if firstname == "" ||
            lastname == "" ||
            email == "" ||
            password == "" ||
            confirmPassword == "" {

            presenter?.presentRegistrationOutcome(response: RegistrationVIP.RegistrationValidation.Response(outcome: Constant.ValidationOutcome.notAllFieldsFilled, isError: true))
        }

        else if Utilities.isPasswordValid(password) == false {
            presenter?.presentRegistrationOutcome(response: RegistrationVIP.RegistrationValidation.Response(outcome: Constant.ValidationOutcome.passwordNotSecure, isError: true))
        }

        else if password != confirmPassword {
            presenter?.presentRegistrationOutcome(response: RegistrationVIP.RegistrationValidation.Response(outcome: Constant.ValidationOutcome.passwordsNotMatch, isError: true))
        }
        
        else {
            worker = RegistrationVIPWorker()
            worker?.registerUser(withEmail: email, password: password, firstname: firstname, lastname: lastname) { [weak self] (outcome, isError) in
                self?.presenter?.presentRegistrationOutcome(response: RegistrationVIP.RegistrationValidation.Response(outcome: outcome, isError: isError))
            }
        }
    }
}
